### ISSUE TITLE
Possible typo?

### ISSUE THREAD

**Issue by londoh** [iget-master/token-auth#1]
Hi

I just saw this flash up on packalyst and thought it might be helpful, so had a quick look

I noticed this...

``` php
    protected function generateAuthorizationToken()
    {
        do {
            $token = str_random();
        } while (Cache::has("auth:${token}"));
        return $token;
    }
```

shouldn't it be: Cache::has("auth:{$token}"))

regards

l.

**Comment by iget-esoares** [comment]
Hi @londoh,

Actually, both ways works:

```
$test = "string";

echo "$test";
echo "${test}";
echo "{$test}";
```

This will print out:

```
stringstringstring
```
