### ISSUE TITLE
Class App\Http\Controllers\Auth\Request does not exist

### ISSUE THREAD

**Issue by ooyo** [iget-master/token-auth#2]
I followed everything readme said, but getting this error  Class App\Http\Controllers\Auth\Request does not exist. Anyone also having this problem?

**Comment by iget-esoares** [comment]
@nuk3dene 
You should include the Request class at top of your php file.

``` php
<?php

namespace App\Http\Controllers\Auth;

use Illuminate\Http\Request;

class YourController { ... }
```

I div improved the README.md to make this clear! :+1: Thanks!
